version: '3'

services:

  laravel:
    image: bitnami/laravel
    container_name: laravel
    networks:
      - laranet
  
  nginx: 
    image: nginx
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge 